Implementation of the Ruby enumerable method
babs257/enumerable-methods pull request #2
Opened 2019-12-21 05:56 UTC by babs257

This is a feature branch of my implementation of Ruby Enumerable Methods

2019-12-23 16:09 UTC, whiz25 requested changes
## Good job :+1: 
You have done a splendid job implementing the requirements for this project. Keep up.
I tested your methods against some edge cases and some have failed. Please look at my comments and implement those changes.

### Martin Afani

2019-12-23 16:15 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns an Enumerator if no block is given. 
You can do this `def my_each return to_enum unless block_given?`

2019-12-23 16:17 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)).
Returns an enumerator if no block is given. Can be implemented as above.

2019-12-23 16:19 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)).
returns an enumerator if no block is given

2019-12-23 16:22 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] when no block or argument is given returns true when none of the collection members are false or nil
- [ ]  when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-12-23 16:24 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ]  when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-12-23 16:25 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] when no block or argument is given returns true only if none of the collection members is true
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-12-23 16:27 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
 - [ ] counts the number of items in enum that are equal to item if an argument is given

2019-12-23 16:29 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] returns an Enumerator if no block is given. do something like `def my_map return to_enum unless block_given?`

2019-12-23 16:29 UTC, whiz25 commented on enumerable.rb
> +    end
- [ ] returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-12-30 19:11 UTC, wathigo requested changes
## Changes Required 
### Hi @babs257  :wave:  
We have a few issues we need to fix before moving on.
See the comments :point_down: 

**Happy Coding :computer: 
Simon Wathigo**

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
**[REQUIRED]** 
* It should return the same thing as Ruby `all?` method. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from the Odin).
* When no block or argument is given returns true when none of the collection members are false or nil.
![Screenshot from 2019-12-30 13-14-40](https://user-images.githubusercontent.com/44072711/71594756-20022b80-2b07-11ea-9a8b-075743601774.png)
* When a class is passed as an argument returns true if all of the collection is a member of such class.
![Screenshot from 2019-12-30 13-21-55](https://user-images.githubusercontent.com/44072711/71594848-7b341e00-2b07-11ea-9119-9fe62deb5528.png)
* When a Regex is passed as an argument returns true if all of the collection matches the Regex.
```
Failure/Error: expect(words.my_all?(/d/)).to be words.all?(/d/)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern.
![Screenshot from 2019-12-30 13-32-03](https://user-images.githubusercontent.com/44072711/71595261-e03c4380-2b08-11ea-8860-7e8ae2e9dfbf.png)

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
**[REQUIRED]**
* Returns the same thing as Ruby's `any?` enumerable method ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from the Odin).
* When no block or argument is given returns true if at least one of the collection is not false or nil.
![Screenshot from 2019-12-30 13-37-18](https://user-images.githubusercontent.com/44072711/71595425-930ca180-2b09-11ea-9252-94494765183f.png)
* When a class is passed as an argument returns true if at least one of the collection is a member of such class.
![Screenshot from 2019-12-30 13-38-43](https://user-images.githubusercontent.com/44072711/71595463-c94a2100-2b09-11ea-9813-0552fa6c6c7d.png)
* When a Regex is passed as an argument returns false if none of the collection matches the Regex.
![Screenshot from 2019-12-30 13-41-10](https://user-images.githubusercontent.com/44072711/71595555-1fb75f80-2b0a-11ea-9822-3699bb6cf02d.png)
* When a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern.
![Screenshot from 2019-12-30 13-42-35](https://user-images.githubusercontent.com/44072711/71595612-5beac000-2b0a-11ea-955a-ecfea45441a2.png)

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
**[REQUIRED]** 
* Returns the same value as Ruby `none?` enumerable method. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from the Odin).
* When no block or argument is given returns true only if none of the collection members is true.
![Screenshot from 2019-12-30 13-46-42](https://user-images.githubusercontent.com/44072711/71595740-df0c1600-2b0a-11ea-97f5-f77ad7ba1032.png)
* When a class is passed as an argument returns true if none of the collection is a member of such class.
![Screenshot from 2019-12-30 13-48-22](https://user-images.githubusercontent.com/44072711/71595808-1bd80d00-2b0b-11ea-9e08-a494636ce30f.png)
* When a Regex is passed as an argument returns true only if none of the collection matches the Regex.
![Screenshot from 2019-12-30 13-49-45](https://user-images.githubusercontent.com/44072711/71595887-65c0f300-2b0b-11ea-9c47-7b5b0399b3c9.png)
* When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern.
![Screenshot from 2019-12-30 13-52-10](https://user-images.githubusercontent.com/44072711/71595959-ab7dbb80-2b0b-11ea-9314-8bcf0b674cf7.png)

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
**[REQUIRED]**
* Returns the same value as Ruby's `count` enumerable method. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from the Odin).
* Counts the number of items in enum that are equal to item if an argument is given.
![Screenshot from 2019-12-30 13-55-57](https://user-images.githubusercontent.com/44072711/71596081-2d6de480-2b0c-11ea-9265-fa26f383f147.png)

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
* Returns the same value as ruby's `map` enumerable method. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from Odin).
* Returns an Enumerator if no block is given.
![Screenshot from 2019-12-30 13-59-27](https://user-images.githubusercontent.com/44072711/71596210-aff6a400-2b0c-11ea-8fe2-3f3f1b0dafde.png)

2019-12-30 19:11 UTC, wathigo commented on enumerable.rb
> +    end
**[REQUIRED]**
* Returns the same value as ruby's `inject` enumerable method. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from Odin).
* Combines all elements of enum by applying a binary operation, specified by a block.
![Screenshot from 2019-12-30 14-05-37](https://user-images.githubusercontent.com/44072711/71596536-b8031380-2b0d-11ea-9221-452683d4aee7.png)
* When a symbol is specified combines each element of the collection by applying the symbol as a named method.
![Screenshot from 2019-12-30 14-09-02](https://user-images.githubusercontent.com/44072711/71596615-ff899f80-2b0d-11ea-9677-1b24450b1ffc.png)

2020-01-15 17:47 UTC, whiz25 requested changes
## Hey @babs257 
I see you have made some changes but still, your methods fail against most edge cases. Please take a look at the comments left by my colleague @wathigo. Please submit another review when done.

### Martin Afani

2020-01-16 04:23 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @babs257  , 👋 You have done a great job in this project 👏 Every test passed successfully.

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">


----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2020-01-16 04:42 UTC, merged